### ISSUE TITLE
能在多点规则吗

### ISSUE THREAD

**Issue by mocos** [thesmallcar/jQuery.easyform#5]
1 length提供一个只有最小限制的规则
2 提供不相等规则
3 提供只有中文规则
4 提供验证手机号规则

**Comment by thesmallcar** [comment]
谢谢支持，稍后的版本里我会考虑你的意见的。
另外也欢迎你参加这个项目，自己动手改代码。
目前的最新代码里，有人添加了mobile规则，不过该规则没有经过仔细的测试，所以手册没有同步更新。

**Comment by BruceWhiteBai** [comment]
请问ajax的提示信息使用data-message-ajax="xxxx"，在ajax的trigger是false时没有显示，应该怎么写啊。

**Comment by thesmallcar** [comment]
额，$("#uid").trigger("easyform-ajax", true); 只是这样就可以了啊！

**Comment by BruceWhiteBai** [comment]
嗯，那天晚上搞出来了，是要这么写的：data-message-ajax="xxx"

**Comment by thesmallcar** [comment]
那就好，多谢支持！

**Comment by BruceWhiteBai** [comment]
规则的匹配可以用js正则验证，主要想用显示的样式
